import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import './globals.css';
import Modal from '@/components/common/modal';

// const pretendard = localFont({
//   src: '../assets/fonts/PretendardVariable.woff2',
//   display: 'swap',
//   weight: '100 900',
//   variable: '--font-pretendard',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={` antialiased`}>
        {children}
        <div id="modal-portal" />
        <Modal />
      </body>
    </html>
  );
}
